# Generated by Django 4.1.5 on 2023-01-25 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("LittleLemonAPI", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="price",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="unit_price",
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_crew",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "Delivery Crew"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_crew",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
