# Generated by Django 4.1.5 on 2023-01-25 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0002_remove_cart_price_remove_orderitem_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="unit_price",
            new_name="price",
        ),
    ]
