# Generated by Django 4.1.5 on 2023-01-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0003_rename_unit_price_cart_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="price",
        ),
    ]
