# Generated by Django 4.1.5 on 2023-01-27 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0004_remove_cart_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="menuitem",
            field=models.ForeignKey(
                blank=None,
                null=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="LittleLemonAPI.menuitem",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.SmallIntegerField(blank=None, null=None),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(
                blank=None, db_index=True, max_length=255, null=None
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                blank=None,
                null=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="LittleLemonAPI.category",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="featured",
            field=models.BooleanField(blank=None, db_index=True, null=None),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(
                blank=None, db_index=True, decimal_places=2, max_digits=6, null=None
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="title",
            field=models.CharField(
                blank=None, db_index=True, max_length=255, null=None
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(auto_now_add=True, db_index=True, null=None),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.BooleanField(blank=None, db_index=True, default=0, null=None),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                blank=None, decimal_places=2, max_digits=6, null=None
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="menuitem",
            field=models.ForeignKey(
                blank=None,
                null=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="LittleLemonAPI.menuitem",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.SmallIntegerField(blank=None, null=None),
        ),
    ]
